# Generated by Django 4.2.1 on 2023-05-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.servicecategory', verbose_name='Категория услуги'),
        ),
    ]
