# Generated by Django 4.2.1 on 2023-05-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_specialization_department'),
        ('service', '0002_alter_service_options_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='department',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='doctor.department'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='service.servicecategory', verbose_name='Категория услуги'),
        ),
    ]
