# Generated by Django 4.2.5 on 2023-10-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Article title')),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('description', models.CharField(max_length=500, verbose_name='Article description')),
                ('content', models.CharField(max_length=5000, verbose_name='Article content')),
                ('link', models.CharField(max_length=500, verbose_name='Article origin link')),
            ],
        ),
    ]
