# Generated by Django 4.2.1 on 2023-05-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_department_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'отделение', 'verbose_name_plural': 'Отделения'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'врача', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'специализацию', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.department', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.specialization', verbose_name='Специализация'),
        ),
    ]
