# Generated by Django 4.2.1 on 2023-05-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_department_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='login',
            field=models.CharField(default='', max_length=25, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=25, verbose_name='Пароль'),
        ),
    ]
