# Generated by Django 4.2.1 on 2023-05-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0012_specialization_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='doctor.department', verbose_name='Отделение'),
        ),
    ]
