# Generated by Django 4.2.1 on 2023-06-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_alter_specialization_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ManyToManyField(related_name='doctors', to='doctor.specialization', verbose_name='Специализация'),
        ),
    ]
