# Generated by Django 4.2.1 on 2023-05-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_servicecategory_department_alter_service_category'),
        ('visit', '0002_remove_visit_price_alter_visit_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AddField(
            model_name='visit',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='Предоставляемая услуга'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(verbose_name='Дата посещения'),
        ),
    ]
