# Generated by Django 4.2.1 on 2023-05-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_alter_visit_options_visit_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='duration',
        ),
    ]
