# Generated by Django 4.2.1 on 2023-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_remove_visit_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.CharField(default='', max_length=50, verbose_name='Диагноз'),
        ),
    ]
