# Generated by Django 4.2.1 on 2023-05-12 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='serial',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Введена несуществующая серия паспорта', regex='^(AB|BM|HB|KH|MP|MC|KB|PP|SP|DP)$')], verbose_name='Серия паспорта'),
        ),
    ]
